/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * @param {Object} event
 * @base onload
 * @returns {Boolean}
*/
app.onload = function() {
	// TODO:: Do your app initialization job
	console.log("loaded");	
};

/**
 * @param {Object} event
 * @base onunload
 * @returns {Boolean}
*/
app.onunload = function() {
	// TODO:: Do your app termination job
	console.log("unloaded");
};

/**
 * @param {Object} event
 * @base onshow
 * @returns {Boolean}
*/
app.onshow = function() {
	// TODO:: Do your job on visible
	console.log("onshown");
};

/**
 * @param {Object} event
 * @base onhide
 * @returns {Boolean}
*/
app.onhide = function() {
	// TODO:: Do your job on invisible
	console.log("onhidden");
};