/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

// page class
/**
*  Object _help_page()
*  @super _page
*  @constructor
*  @memberOf _help_page 
*/
function _help_page() {
}

//inherit _page
_help_page.prototype = new _page("help");

// widget assist
_help_page.prototype.header1 = undefined;
_help_page.prototype.backButton = undefined;
_help_page.prototype.content1 = undefined;

// default widget event handler
_help_page.prototype.backButton_ontap = function(event) {};

_help_page.prototype.init_page = function(isStartPage, htmlPath, cssPath, managedCssPath) {
	this.htmlPath = htmlPath;
	this.cssPath = cssPath;
	this.managedCssPath = managedCssPath;
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_help_page.prototype.header1 = $("#help #header1");

		/**
		 * @type jQueryObject
		 */
		_help_page.prototype.backButton = $("#help #backButton");

		/**
		 * @type jQueryObject
		 */
		_help_page.prototype.content1 = $("#help #content1");

		// bind widget event handler
		_help_page.prototype.backButton.bind("tap", function(event) { _help_page.prototype.backButton_ontap(event); });

	}, isStartPage);

};
