/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * @param {Object} event
 * @base _help_page
 * @returns {Boolean}
*/
_help_page.prototype.backButton_ontap = function(event) {
	pageManager.changePage('settings', {transition: 'fade'});
};

