/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * Add new alert to history
 */
function addNewAlert() {
	
}


/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.onpagebeforehide = function(event) {
	console.log('history page before hide');
	stop();
};

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.onpagebeforeshow = function(event) {
	console.log('history page before show');
	start();
};

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.backButton_ontap = function(event) {
	pageManager.changePage('list');
};

function test() {
	console.log('ee');
	
	//var matcher = new Matcher();
	//var packages = [];
	function info(msg) {
		document.getElementById("info").innerText = msg;
	}
	matcher.setDebugHandler(info);
	function startSampling() {
		matcher.startSampling();
		console.log("matcher.startSampling();");
	}
	function stopSampling() {
		var samplePackage = matcher.stopSampling();
		console.log("matcher.stopSampling();");
		packages.push(samplePackage);
		console.log("package received #" + packages.length);
	}
	
	function sampleMatched(sampleIndex) {
		console.log("sample matched #" + sampleIndex);
	}
	function startMatching() {
		matcher.startMatching(packages, sampleMatched);
		console.log("matcher.startMatching(packages, sampleMatched);");
	}
	function stopMatching() {
		matcher.stopMatching();
		console.log("matcher.stopMatching();");
	}
	
	
	
	
	//$('#notification').notification('open');
//	$( "div.test" ).on("pagecreate", function () {
//		$('#noti-demo').on('vmouseup', function ( e ) {
//			$('#notification').notification('open');
//		});
//
//		$('#noti-icon1').on('vclick', function ( e ) {
//			$('#notification').notification('icon', './test/icon02.png');
//		});
//
//		$('#noti-icon2').on('vclick', function ( e ) {
//			$('#notification').notification('icon', './test/icon01.png');
//		});
//
//	});
}