/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

// page class
/**
*  Object _history_page()
*  @super _page
*  @constructor
*  @memberOf _history_page 
*/
function _history_page() {
}

//inherit _page
_history_page.prototype = new _page("history");

// widget assist
_history_page.prototype.header1 = undefined;
_history_page.prototype.backButton = undefined;
_history_page.prototype.trashButton = undefined;
_history_page.prototype.content1 = undefined;
_history_page.prototype.alertList = undefined;

// default widget event handler
_history_page.prototype.backButton_ontap = function(event) {};
_history_page.prototype.trashButton_ontap = function(event) {};

_history_page.prototype.init_page = function(isStartPage, htmlPath, cssPath, managedCssPath) {
	this.htmlPath = htmlPath;
	this.cssPath = cssPath;
	this.managedCssPath = managedCssPath;
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_history_page.prototype.header1 = $("#history #header1");

		/**
		 * @type jQueryObject
		 */
		_history_page.prototype.backButton = $("#history #backButton");

		/**
		 * @type jQueryObject
		 */
		_history_page.prototype.trashButton = $("#history #trashButton");

		/**
		 * @type jQueryObject
		 */
		_history_page.prototype.content1 = $("#history #content1");

		/**
		 * @type jQueryObject
		 */
		_history_page.prototype.alertList = $("#history #alertList");

		// bind widget event handler
		_history_page.prototype.backButton.bind("tap", function(event) { _history_page.prototype.backButton_ontap(event); });
		_history_page.prototype.trashButton.bind("tap", function(event) { _history_page.prototype.trashButton_ontap(event); });

	}, isStartPage);

};
