/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * Add new alert to history
 */
function addNewAlert() {
    
}

function historyMatchHandler( event, soundID ) {
	console.log( 'history matchHandler', soundID );
	var sound = getSoundByID( soundID );
	
	var date = new Date;
	// TODO
	
	
	// check history list
	// check time stamp 
	// push history list
	
	
    var noti = {
            id : sound.id,
            message : sound.title,
            vibration : true // FIXME: sound..alertMethods[0], [1] check
    }
    notification(noti);

    updateHistoryList(sound)
}

function updateHistoryList(sound) {
	// TODO:
	var historyListView = $('#alertList');
	var li = '<li><img src="../res/thumbnail.jpg" alt="icon" class="ui-li-bigicon">' + sound.title + '<span class="ui-li-text-sub">' + 'Sub text' + '</span></li>';
	historyListView.append(li).listview('refresh');

}

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.onpagebeforehide = function(event) {
    console.log('history page before hide');
    stop();
    listenerApp.off('soundMatched', historyMatchHandler);
};

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.onpagebeforeshow = function(event) {
    console.log('history page before show');
    start();

    listenerApp.on('soundMatched', historyMatchHandler);
};

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.backButton_ontap = function(event) {
    pageManager.changePage('list');
};

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.trashButton_ontap = function(event) {
    // TODO
};

