/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * Add new alert to history
 */
function addNewAlert() {
	
}

function test() {
	
	// FIXME::
	$('#notification').notification('open').on("click", function(){alert('open')});
	//$('#notification2').notification('open');
//	$( "div.test" ).on("pagecreate", function () {
//		$('#noti-demo').on('vmouseup', function ( e ) {
//			$('#notification').notification('open');
//		});
//
//		$('#noti-icon1').on('vclick', function ( e ) {
//			$('#notification').notification('icon', './test/icon02.png');
//		});
//
//		$('#noti-icon2').on('vclick', function ( e ) {
//			$('#notification').notification('icon', './test/icon01.png');
//		});
//
//	});
}

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.onpagebeforehide = function(event) {
	console.log('history page before hide');
	stop();
};

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.onpagebeforeshow = function(event) {
	console.log('history page before show');
	start();
};

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.backButton_ontap = function(event) {
	pageManager.changePage('list');
};

/**
 * @param {Object} event
 * @base _history_page
 * @returns {Boolean}
*/
_history_page.prototype.trashButton_ontap = function(event) {
	// TODO
};

