/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * @param {Object} event
 * @base _intro_page
 * @returns {Boolean}
*/
_intro_page.prototype.button1_ontap = function(event) {
	pageManager.changePage('list');
};

/**
 * @param {Object} event
 * @base _intro_page
 * @returns {Boolean}
*/
_intro_page.prototype.onpageshow = function(event) {
	console.log('intro page show');
	setTimeout(function () {
		console.log('go to list');
		pageManager.changePage('list');
	}, 3000);
};

