/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * @param {Object} event
 * @base _intro_page
 * @returns {Boolean}
*/
_intro_page.prototype.button1_ontap = function(event) {
	pageManager.changePage('list', {transition: 'fade'});
};

/**
 * @param {Object} event
 * @base _intro_page
 * @returns {Boolean}
*/
_intro_page.prototype.introImage_ontap = function(event) {
	pageManager.changePage('list', {transition: 'fade'});
};

