/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.startButton_ontap = function(event) {
	pageManager.changePage('history', {});
};

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.newSoundButton_ontap = function(event) {
	pageManager.changePage('newsound', {});
};

