/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/


var editPopup;

function updateSoundList(soundListView) {
	soundListView.children().remove();
	for (var i in listenerApp.soundList) {
		var sound = listenerApp.soundList[i];
		var li = $('<li>').text(sound.title);
		soundListView.append(li);
	}
}

function initEditPopup(content) {
	// Add sound edit popup and initialize it
	editPopup = $('<div data-role="popup" id="soundDialog"><form>Edit Sound</form></div>');
	content.append(editPopup);
	editPopup.popup();

//	editPopup.load('./editPopup.html', '', function () {
//		console.log('load editPopup', arguments);
//		editPopup.popup();
//	});
}

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.startButton_ontap = function(event) {
	pageManager.changePage('history', {});
};

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.newSoundButton_ontap = function(event) {
	pageManager.changePage('newsound', {});
};

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.onpagebeforeshow = function(event) {
	updateSoundList(this.soundListView);
};

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.settingsButton_ontap = function(event) {
	pageManager.changePage('settings');
};

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.soundListView_ontap = function(event) {
	console.log('soundListView tap');
};

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.soundListView_ontaphold = function(event) {
	console.log('soundListView taphold');
	$('#soundDialog').popup('open');
//
//	var form = editPopup.children('form');
//	var playButton = $('<input value="Play" type="button">');
//	playButton.button({show: true});
////	playButton.button('option', );
////	playButton.button('enable');
////	playButton.button('refresh');
////	var titleInput = $('<input data-inline="true" value="" type="text">');
////	titleInput.textinput();
//	var delButton = $('<input data-icon="delete" data-inline="true" data-iconpos="notext" value="Icon only" type="button">');
//	delButton.button();
////	form.append(playButton, titleInput, delButton);
//	form.append(playButton, delButton);
};

/**
 * @param {Object} event
 * @base _list_page
 * @returns {Boolean}
*/
_list_page.prototype.onpageinit = function(event) {
//	initEditPopup(this.content);
};

