/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/
var isRecording = false;
var samplePackage;
var analyser;
function startRecord() {
    // draw canvas
    analyser = matcher.createAnalyser("soundCanvas", 0.0, 0.5);
    matcher.startAnalyser(analyser);

    matcher.startSampling();
    console.log("matcher.startSampling();");
    isRecording = true;
}

function stopRecord() {
    samplePackage = matcher.stopSampling();
    console.log("matcher.stopSampling();");
    console.log("package received #" + samplePackage.length, samplePackage);
    isRecording = false;

    // stop draw canvas
    matcher.stopAnalyser(analyser);
}

/**
 * @param {Object} event
 * @base _newsound_page
 * @returns {Boolean}
*/
_newsound_page.prototype.okButton_ontap = function(event) {
    console.log('ok button tap');
    console.log('sound title:' + this.soundTitle.val());
    var title = this.soundTitle.val();
    if ( title === '' || !samplePackage ) {
        $('#center_info').popup("open");
        return;
    }

    addNewSound(title, '', samplePackage);
    pageManager.changePage('list', {transition: 'fade'});
};

/**
 * @param {Object} event
 * @base _newsound_page
 * @returns {Boolean}
*/
_newsound_page.prototype.cancelButton_ontap = function(event) {
    console.log('cancel button tap');
    pageManager.changePage('list', {transition: 'fade'});
};

/**
 * @param {Object} event
 * @base _newsound_page
 * @returns {Boolean}
*/
_newsound_page.prototype.recordButton_ontap = function(event) {
    console.log('record button tap');

    if ( isRecording == false ) {
        startRecord();
        $('#recordButton .ui-btn-text').html('Stop');
    } else {
        stopRecord();
        $('#recordButton .ui-btn-text').html('Record');
    }
};

/**
 * @param {Object} event
 * @base _newsound_page
 * @returns {Boolean}
*/
_newsound_page.prototype.backButton_ontap = function(event) {
    pageManager.changePage('list', {transition: 'fade'});
};

/**
 * @param {Object} event
 * @base _newsound_page
 * @returns {Boolean}
*/
_newsound_page.prototype.onpageinit = function(event) {
    samplePackage = null;
};

/**
 * @param {Object} event
 * @base _newsound_page
 * @returns {Boolean}
*/
_newsound_page.prototype.onpageshow = function(event) {
    // set default title generated from new sound id
    var newSoundID = generateNewSoundID();
    var defaultTitle = 'Sound Sample #' + newSoundID;
    this.soundTitle.val(defaultTitle);
    this.soundTitle.focus();
};
