/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

// page class
/**
*  Object _newsound_page()
*  @super _page
*  @constructor
*  @memberOf _newsound_page 
*/
function _newsound_page() {
}

//inherit _page
_newsound_page.prototype = new _page("newsound");

// widget assist
_newsound_page.prototype.newSoundHeader = undefined;
_newsound_page.prototype.content1 = undefined;
_newsound_page.prototype.soundTitle = undefined;
_newsound_page.prototype.soundView = undefined;
_newsound_page.prototype.recordButton = undefined;
_newsound_page.prototype.okButton = undefined;
_newsound_page.prototype.cancelButton = undefined;

// default widget event handler
_newsound_page.prototype.recordButton_ontap = function(event) {};
_newsound_page.prototype.okButton_ontap = function(event) {};
_newsound_page.prototype.cancelButton_ontap = function(event) {};

_newsound_page.prototype.init_page = function(isStartPage, htmlPath, cssPath, managedCssPath) {
	this.htmlPath = htmlPath;
	this.cssPath = cssPath;
	this.managedCssPath = managedCssPath;
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_newsound_page.prototype.newSoundHeader = $("#newsound #newSoundHeader");

		/**
		 * @type jQueryObject
		 */
		_newsound_page.prototype.content1 = $("#newsound #content1");

		/**
		 * @type jQueryObject
		 */
		_newsound_page.prototype.soundTitle = $("#newsound #soundTitle");

		/**
		 * @type jQueryObject
		 */
		_newsound_page.prototype.soundView = $("#newsound #soundView");

		/**
		 * @type jQueryObject
		 */
		_newsound_page.prototype.recordButton = $("#newsound #recordButton");

		/**
		 * @type jQueryObject
		 */
		_newsound_page.prototype.okButton = $("#newsound #okButton");

		/**
		 * @type jQueryObject
		 */
		_newsound_page.prototype.cancelButton = $("#newsound #cancelButton");

		// bind widget event handler
		_newsound_page.prototype.recordButton.bind("tap", function(event) { _newsound_page.prototype.recordButton_ontap(event); });
		_newsound_page.prototype.okButton.bind("tap", function(event) { _newsound_page.prototype.okButton_ontap(event); });
		_newsound_page.prototype.cancelButton.bind("tap", function(event) { _newsound_page.prototype.cancelButton_ontap(event); });

	}, isStartPage);

};
