/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

// page class
/**
*  Object _settings_page()
*  @super _page
*  @constructor
*  @memberOf _settings_page 
*/
function _settings_page() {
}

//inherit _page
_settings_page.prototype = new _page("settings");

// widget assist
_settings_page.prototype.header1 = undefined;
_settings_page.prototype.backButton = undefined;
_settings_page.prototype.content1 = undefined;
_settings_page.prototype.helpButton = undefined;
_settings_page.prototype.checkboxes1 = undefined;
_settings_page.prototype.checkboxitem1 = undefined;
_settings_page.prototype.checkboxitem2 = undefined;

// default widget event handler

_settings_page.prototype.init_page = function(isStartPage, htmlPath, cssPath, managedCssPath) {
	this.htmlPath = htmlPath;
	this.cssPath = cssPath;
	this.managedCssPath = managedCssPath;
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.header1 = $("#settings #header1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.backButton = $("#settings #backButton");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.content1 = $("#settings #content1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.helpButton = $("#settings #helpButton");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.checkboxes1 = $("#settings #checkboxes1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.checkboxitem1 = $("#settings #checkboxitem1");

		/**
		 * @type jQueryObject
		 */
		_settings_page.prototype.checkboxitem2 = $("#settings #checkboxitem2");

		// bind widget event handler

	}, isStartPage);

};
